# Generated by Django 3.0.5 on 2020-06-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
