# Generated by Django 3.0.5 on 2020-06-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200602_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
