# Generated by Django 3.0.5 on 2020-06-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200602_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='image',
        ),
    ]
