# Generated by Django 3.0.5 on 2020-06-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200604_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
