# Generated by Django 3.0.5 on 2020-06-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='due_date',
        ),
    ]
