# Generated by Django 3.0.5 on 2020-08-12 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Item'),
        ),
    ]
