# Generated by Django 3.0.5 on 2020-08-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200817_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
