# Generated by Django 3.0.5 on 2020-08-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rating_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.CharField(blank=True, default=0, max_length=120, null=True),
        ),
    ]
