# Generated by Django 3.0.5 on 2020-08-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200817_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
